"""Build one review sheet of all jobs, rubrics and base resumes for applicant review.

Usage:
    python scripts/make_review_sheet.py

Writes docs/review/review_sheet.md. The sheet is generated from the
data files, so it always matches what the pipeline will actually use.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

from fairhire.data_io import load_jobs, load_resumes, load_rubrics  # noqa: E402
from fairhire.render_resumes import render_text  # noqa: E402

OUT = REPO / "docs" / "review" / "review_sheet.md"


def cell(text: str) -> str:
    return text.replace("|", "/").replace("\n", " ")


def main() -> None:
    jobs, rubrics, resumes = load_jobs(), load_rubrics(), load_resumes()
    out: list[str] = [
        "# Review sheet: jobs, rubrics and base resumes",
        "",
        "Generated by `scripts/make_review_sheet.py` from the files in `data/`. "
        "Edit the YAML files, not this sheet, then run the script again.",
        "",
        "Rubric scale: 0 = no evidence, 1 = mentioned only, 2 = applied, 3 = applied with depth "
        "and a stated outcome.",
        "",
        "## Jobs and rubrics",
    ]
    for job_id, job in jobs.items():
        rubric = rubrics[job_id]
        out += ["", f"### {job_id}: {job.title} ({job.employer})", "", job.summary.strip(), "",
                "**Requirements in the posting:**", ""]
        out += [f"- {r}" for r in job.requirements]
        if job.nice_to_have:
            out += ["", "**Nice to have:** " + " ".join(job.nice_to_have)]
        out += ["", f"**Rubric {rubric.rubric_id}** ({rubric.status})", "",
                "| Competency | Importance | Weight | Counts as evidence | Does not count |",
                "|---|---|---|---|---|"]
        for c in rubric.competencies:
            out.append(f"| {cell(c.name)} | {c.importance.value} | {c.weight:.2f} | "
                       f"{cell(' '.join(c.observable_evidence))} | {cell(' '.join(c.does_not_count))} |")
    out += ["", "Signals every rubric treats as irrelevant:", ""]
    out += [f"- {s}" for s in next(iter(rubrics.values())).irrelevant_signals]

    out += ["", "## Base resumes", ""]
    for rid, resume in resumes.items():
        tiers = ", ".join(f"{j}: {t.value}" for j, t in resume.intended_tier.items())
        out += [f"### {rid} (intended tiers: {tiers})", "",
                f"*Design notes (never shown to a model):* {resume.design_notes.strip()}", "",
                "```text", render_text(resume).rstrip(), "```", ""]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
